"""init

Revision ID: 3bb3272badb4
Revises: 
Create Date: 2026-08-14 18:18:56.552155

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '3bb3272badb4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
